name: Build and Test

on:
  push:
    branches: [ master ]

env:
  SCHEME: Survey
  TEST_DEVICE: platform=iOS Simulator,name=iPhone 11,OS=15.0

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
    - name: Checkout project repo
      uses: actions/checkout@v2

    - name: Build
      shell: bash
      run: xcodebuild -scheme '${{ env.SCHEME }}' -sdk iphonesimulator -destination '${{ env.TEST_DEVICE }}' build

  test:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
    - name: Checkout project repo
      uses: actions/checkout@v2

    - name: Test
      shell: bash
      run: xcodebuild -scheme '${{ env.SCHEME }}' -sdk iphonesimulator -destination '${{ env.TEST_DEVICE }}' test
